---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-mailserver-spf-config
data:
  policyd-spf.conf: |
    debugLevel = 1
    TestOnly = 1

    HELO_reject = SPF_Not_Pass
    Mail_From_reject = Fail

    PermError_reject = False
    TempError_Defer = False

    skip_addresses = 127.0.0.0/8,::ffff:127.0.0.0//104,::1

    # Whitelist (optional - uncomment and configure if needed)
    # Whitelist = ${CONFIG_NGINX_WHITELIST}

    # Custom rejection message
    Header_Type = SPF
    Authserv_Id = ${SECRET_DOMAIN}
