---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ldap-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ldap-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        LDAP_BIND_DN: "{{ .LDAP_BIND_DN }}"
        LDAP_BIND_PW: "{{ .LDAP_BIND_PW }}"
        LDAP_SEARCH_BASE: "{{ .LDAP_SEARCH_BASE }}"
  dataFrom:
    - extract:
        key: DOCKER_MAILSERVER
